name: Release
description: Create a GitHub release

on:
  push:
    tags:
      - 'v*'  # Trigger on versioned tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          version=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.VERSION }}" --repo "$GITHUB_REPOSITORY" --notes "Automated release for version v${{ env.VERSION }}"

      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "v${{ env.VERSION }}" dist/** --repo "$GITHUB_REPOSITORY"
