name: Publish
description: Publish the package to PyPI

runs:
    using: "composite"
    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=$(echo "${OWNER}" | tr '[:upper:]' '[:lower:]')" >> "${GITHUB_ENV}"
        env:
          OWNER: '${{ github.repository_owner }}'
        shell: bash
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1