name: Publish
description: Publish the package to PyPI

runs:
  using: "composite"
  steps:
    - name: Set lowercase repository owner
      run: |
        echo "OWNER=$(echo \"${OWNER}\" | tr '[:upper:]' '[:lower:]')" >> "${GITHUB_ENV}"
        echo "REPO_NAME=$(echo \"${GITHUB_REPOSITORY}\" | tr '[:upper:]' '[:lower:]')" >> "${GITHUB_ENV}"
      env:
        OWNER: '${{ github.repository_owner }}'
        GITHUB_REPOSITORY: '${{ github.repository }}'
      shell: bash

    - name: Debug variables
      run: |
        echo "OWNER=${OWNER}"
        echo "REPO_NAME=${REPO_NAME}"
      shell: bash

    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      env:
        GITHUB_REPOSITORY: ${{ env.OWNER }}/${{ env.REPO_NAME }}
