name: Publish
description: Publish the package to PyPI

runs:
    using: "composite"
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          repository-url: https://upload.pypi.org/legacy/
          packages-dir: dist
          verify-metadata: true
          skip-existing: false
          verbose: false
          print-hash: false
          attestations: true
          docker-image: ghcr.io/sm00thix/ikpls:latest