name: Publish

runs:
    using: "composite"
    steps:
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          python -m pip install build --user
          pip install -U "jax[cpu]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
        shell: bash  

      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/