name: Python Package
on:
    workflow_run:
        workflows: ["Tests"]
        types:
            - completed
jobs:
    build_package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/build
    publish_package:
        needs: build_package
        runs-on: ubuntu-latest
        # if: ${{ github.event.workflow_run.conclusion == 'success' }}
        environment:
            name: pypi
            url: https://pypi.org/p/ikpls
        permissions:
            id-token: write
        steps:  
            - uses: actions/checkout@v4
            - uses: ./.github/actions/publish
    github_release:
        needs: publish_package
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: ./github/actions/release

